name: Build_Beta_BTG_CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install React Dependencies
        working-directory: React
        run: npm install --legacy-peer-deps

      - name: Build React
        working-directory: React
        run: npm run build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore .NET Packages
        working-directory: API/UserPanel
        run: dotnet restore

      - name: Publish .NET
        working-directory: API/UserPanel
        run: dotnet publish -c Release -o publish

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        working-directory: Python
        run: pip install -r requirements.txt

      - name: Commit Build Output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add React/build
          git add API/UserPanel/publish

          git commit -m "UPDATED-$(TZ='Asia/Kolkata' date +'%d-%m-%Y- %H:%M:%S')" || exit 0

          git push origin main

      - name: Clone Repo_3
        run: |
          git clone https://x-access-token:${{ secrets.BUILD_READY_TOKEN }}@github.com/UmaTechspire/BETA_BTG_READY.git ready

    # React Build -> frontend/build
      - name: Copy React Build
        run: |
          mkdir -p ready/frontend
          cp -r React/build ready/frontend/

      # Publish Output -> dnbackend
      - name: Copy DotNet Publish
        run: |
          mkdir -p ready/dnbackend
          cp -r API/UserPanel/publish/* ready/dnbackend/

      # Python app -> pybackend/app
      - name: Copy Python App
        run: |
          mkdir -p ready/pybackend
          cp -r Python/app/* ready/pybackend/app/

      # Remove Python Cache
      - name: Clean Python Cache
        run: |
          find ready/pybackend -name "__pycache__" -type d -exec rm -rf {} +
          find ready/pybackend -name "*.pyc" -delete

      # Push Repo3
      - name: Commit And Push Repo3
        run: |
          cd ready

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${{ secrets.BUILD_READY_TOKEN }}@github.com/UmaTechspire/BETA_BTG_READY.git

          git add .

          git commit -m "UPDATED-$(TZ='Asia/Kolkata' date +'%d-%m-%Y- %H:%M:%S')" || exit 0

          git push origin main