name: Build_Beta_BTG_CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  react-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: React

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build React
        run: npm run build

      - name: Commit React Build
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add build

          git commit -m "React Build Updated [skip ci]" || exit 0
          git push

  dotnet-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: API/UserPanel

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Packages
        run: dotnet restore

      - name: Publish Application
        run: dotnet publish -c Release -o publish

      - name: Commit Publish Folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add publish

          git commit -m ".NET Publish Updated [skip ci]" || exit 0
          git push

  python-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Python

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt